# pre-commit run --all --show-diff-on-failure --verbose --color always
exclude: "^web/"
default_language_version:
  python: python3
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: trailing-whitespace
    exclude: /README\.rst$|\.pot?$
  - id: end-of-file-fixer
    exclude: /README\.rst$|\.pot?$
  - id: debug-statements
  - id: flake8
    name: flake8 except __init__.py, settings.py, conftest.py, env.py, engine.py and rearq
    exclude: (/__init__\.py$|/(jwt_)?settings\.py$|/conftest\.py$|/engine\.py$|/env\.py$|/rearq\.py$)
    args: ["--extend-ignore=B008"]
    additional_dependencies: ["flake8-bugbear==19.8.0"]
  - id: flake8
    name: flake8 only rearq
    files: /rearq\.py$
    args: ["--extend-ignore=F401"]
  - id: flake8
    name: flake8 only __init__.py,conftest.py, env and engine
    args: ["--extend-ignore=F401,F403"]  # ignore unused imports in __init__.py
    files: (/__init__\.py$|/conftest\.py$|/engine\.py$|/env\.py$)
  - id: flake8
    name: flake8 only settings.py
    args: ["--extend-ignore=B902"]  # ignore unused imports in __init__.py
    files: /(jwt_)?settings\.py$
  - id: fix-encoding-pragma
    args: ["--remove"]
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-xml
  - id: mixed-line-ending
    args: ["--fix=lf"]
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v5.10.1
  hooks:
  - id: isort
    name: isort
- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v6.5.1
  hooks:
  - id: eslint
    verbose: true
